// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportiviDBOneToMany.Models;

#nullable disable

namespace SportiviDBOneToMany.Migrations
{
    [DbContext(typeof(SportDbContext))]
    [Migration("20240220184632_2")]
    partial class _2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SportiviDBOneToMany.Models.Sport", b =>
                {
                    b.Property<int>("SportID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SportID"));

                    b.Property<string>("SportNume")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SportID");

                    b.ToTable("sporturi");
                });

            modelBuilder.Entity("SportiviDBOneToMany.Models.Sportiv", b =>
                {
                    b.Property<int>("SportivID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SportivID"));

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SportId")
                        .HasColumnType("int");

                    b.HasKey("SportivID");

                    b.HasIndex("SportId");

                    b.ToTable("sportivi");
                });

            modelBuilder.Entity("SportiviDBOneToMany.Models.Sportiv", b =>
                {
                    b.HasOne("SportiviDBOneToMany.Models.Sport", "Sport")
                        .WithMany("Sportivi")
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sport");
                });

            modelBuilder.Entity("SportiviDBOneToMany.Models.Sport", b =>
                {
                    b.Navigation("Sportivi");
                });
#pragma warning restore 612, 618
        }
    }
}
