// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TariDBOneToMany.Models;

#nullable disable

namespace TariDBOneToMany.Migrations
{
    [DbContext(typeof(TariDbContext))]
    [Migration("20240221185049_unu")]
    partial class unu
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TariDBOneToMany.Models.Locuitor", b =>
                {
                    b.Property<int>("LocuitorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocuitorID"));

                    b.Property<string>("NumeLocuitor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TaraId")
                        .HasColumnType("int");

                    b.Property<int?>("VarstaLocuitor")
                        .HasColumnType("int");

                    b.HasKey("LocuitorID");

                    b.HasIndex("TaraId");

                    b.ToTable("locuitori");
                });

            modelBuilder.Entity("TariDBOneToMany.Models.Tara", b =>
                {
                    b.Property<int>("TaraID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaraID"));

                    b.Property<string>("TaraNume")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TaraID");

                    b.ToTable("tari");
                });

            modelBuilder.Entity("TariDBOneToMany.Models.Locuitor", b =>
                {
                    b.HasOne("TariDBOneToMany.Models.Tara", "Tara")
                        .WithMany("Locuitori")
                        .HasForeignKey("TaraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tara");
                });

            modelBuilder.Entity("TariDBOneToMany.Models.Tara", b =>
                {
                    b.Navigation("Locuitori");
                });
#pragma warning restore 612, 618
        }
    }
}
